# Generated by Django 4.0.4 on 2022-04-29 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_post', models.DateField(default=django.utils.timezone.now)),
                ('atividade_doc', models.FileField(upload_to='atividade_postada/%Y/%m', verbose_name='Atividade')),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.CharField(max_length=250)),
                ('conteudo', models.TextField()),
                ('conteudo_download', models.FileField(blank=True, null=True, upload_to='conteudo_aula/%Y/%m')),
                ('data_post', models.DateField(default=django.utils.timezone.now)),
                ('aula_gravada', models.FileField(upload_to='aula/%Y/%m')),
                ('img_aula', models.ImageField(blank=True, null=True, upload_to='img_aula/%Y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='ClassePalavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Contexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingua', models.CharField(max_length=20)),
                ('lingua_img', models.ImageField(blank=True, null=True, upload_to='img_lingua')),
            ],
        ),
        migrations.CreateModel(
            name='NivelLingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=2)),
                ('valor_nivel', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Nível de língua',
                'verbose_name_plural': 'Níveis de língua',
            },
        ),
        migrations.CreateModel(
            name='Palavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=40)),
                ('significado', models.CharField(max_length=255)),
                ('escrita_fonetica', models.CharField(blank=True, max_length=50, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.classepalavra')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.pessoa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PalavraContexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.contexto')),
                ('palavra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensino.palavra')),
            ],
        ),
        migrations.AddField(
            model_name='palavra',
            name='contexto',
            field=models.ManyToManyField(related_name='palavras', through='ensino.PalavraContexto', to='ensino.contexto'),
        ),
        migrations.AddField(
            model_name='palavra',
            name='lingua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ensino.lingua'),
        ),
        migrations.AddField(
            model_name='palavra',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.nivellingua'),
        ),
        migrations.CreateModel(
            name='EnvioAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField(default=django.utils.timezone.now)),
                ('envio_atividade_doc', models.FileField(upload_to='atividade_enviada/%Y/%m')),
                ('nota', models.FloatField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('envio_definitivo', models.BooleanField(default=False)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atividades_enviadas', to='ensino.atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.usuarioensino')),
            ],
            options={
                'verbose_name': 'Atividade enviada',
                'verbose_name_plural': 'Atividades enviadas',
            },
        ),
        migrations.AddField(
            model_name='classepalavra',
            name='lingua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.lingua'),
        ),
        migrations.CreateModel(
            name='AulaPalavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensino.aula')),
                ('palavra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.palavra')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='autor_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.usuarioensino'),
        ),
        migrations.AddField(
            model_name='aula',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.nivellingua'),
        ),
        migrations.AddField(
            model_name='aula',
            name='palavra',
            field=models.ManyToManyField(related_name='aulas', through='ensino.AulaPalavra', to='ensino.palavra'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividade', to='ensino.aula'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.usuarioensino'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.pessoa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
