# Generated by Django 4.0.4 on 2022-04-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_img_usuario'),
        ('ensino', '0002_aula_lingua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='autor_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario'),
        ),
    ]
