# Generated by Django 4.0.4 on 2022-04-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0003_alter_aula_autor_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='is_licenced',
            field=models.BooleanField(default=False),
        ),
    ]
