# Generated by Django 4.0.4 on 2022-04-30 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_is_licenced'),
        ('ensino', '0004_aula_is_licenced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='usuario',
        ),
        migrations.AddField(
            model_name='atividade',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario'),
        ),
    ]
