# Generated by Django 4.0.4 on 2022-05-01 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_is_licenced'),
        ('ensino', '0006_remove_envioatividade_usuario_envioatividade_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.aula')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(max_length=255)),
                ('resposta', models.CharField(max_length=60)),
                ('errada_1', models.CharField(max_length=60)),
                ('errada_2', models.CharField(max_length=60)),
                ('errada_3', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='EnvioAtividadeAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovado', models.BooleanField(default=False)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.atividadeaula')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.atividadeaula')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.questao')),
            ],
        ),
        migrations.AddField(
            model_name='atividadeaula',
            name='questao',
            field=models.ManyToManyField(related_name='atividade', through='ensino.AtividadeQuestao', to='ensino.questao'),
        ),
    ]
