# Generated by Django 4.0.4 on 2022-05-01 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0007_atividadeaula_questao_envioatividadeaula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='errada_1',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='errada_2',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='errada_3',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='resposta',
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.CharField(max_length=60)),
                ('is_correct', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.questao')),
            ],
        ),
    ]
