# Generated by Django 4.0.4 on 2022-05-01 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0008_remove_questao_errada_1_remove_questao_errada_2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alternativa',
        ),
    ]
