# Generated by Django 4.0.4 on 2022-05-02 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_is_licenced'),
        ('ensino', '0010_alternativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='questao',
            name='lingua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.lingua'),
        ),
        migrations.AddField(
            model_name='questao',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.nivellingua'),
        ),
    ]
