# Generated by Django 4.0.4 on 2022-05-03 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_is_licenced'),
        ('ensino', '0012_alter_questao_lingua_alter_questao_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingua', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.lingua')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.nivellingua')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
