# Generated by Django 4.0.4 on 2022-05-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0013_usuariolingua'),
    ]

    operations = [
        migrations.AddField(
            model_name='envioatividadeaula',
            name='nota',
            field=models.FloatField(default=0.0),
        ),
    ]
