# Generated by Django 4.0.4 on 2022-05-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0014_envioatividadeaula_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envioatividadeaula',
            name='nota',
            field=models.FloatField(),
        ),
    ]
