# Generated by Django 4.0.4 on 2022-05-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0018_alter_usuariolingua_lingua_alter_usuariolingua_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivellingua',
            name='img_nivel',
            field=models.ImageField(blank=True, null=True, upload_to='img_nivel/%Y/%m'),
        ),
    ]
