# Generated by Django 4.0.4 on 2022-05-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0019_nivellingua_img_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivellingua',
            name='img_nivel',
        ),
    ]
