# Generated by Django 4.0.4 on 2022-05-25 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0020_remove_nivellingua_img_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloLinguaNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('img_modulo', models.ImageField(blank=True, null=True, upload_to='img_modulo/%Y/%m')),
                ('lingua', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.lingua')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.nivellingua')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='modulo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.modulolinguanivel'),
        ),
    ]
