# Generated by Django 4.0.4 on 2022-05-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0021_modulolinguanivel_aula_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envioatividade',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='envioatividade',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='EnvioAtividade',
        ),
    ]
