# Generated by Django 4.0.4 on 2022-05-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0022_remove_envioatividade_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='img_aula',
            field=models.ImageField(blank=True, default='img_aula/default.jpg', null=True, upload_to='img_aula/%Y/%m'),
        ),
    ]
