# Generated by Django 4.0.4 on 2022-05-30 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0023_alter_aula_img_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='palavra',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
