# Generated by Django 4.0.4 on 2022-05-31 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0024_palavra_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeaula',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atividade', to='ensino.aula'),
        ),
    ]
