# Generated by Django 4.0.4 on 2022-06-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0025_alter_atividadeaula_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='conteudo_download',
        ),
    ]
