# Generated by Django 4.0.4 on 2022-04-29 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ensino', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_postagem', models.CharField(max_length=60)),
                ('conteudo_postagem', models.TextField()),
                ('imagem_postagem', models.ImageField(upload_to='blog/postagem/%Y/%m')),
                ('data_postagem', models.DateField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario')),
                ('lingua', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ensino.lingua')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_noticia', models.CharField(max_length=50)),
                ('conteudo_noticia', models.TextField()),
                ('data_post', models.DateField(default=django.utils.timezone.now)),
                ('imagem_noticia', models.ImageField(upload_to='img_noticia/%Y/%m')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('imagem_mensagem', models.ImageField(blank=True, null=True, upload_to='chat/%Y/%m')),
                ('data_envio', models.DateField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.conversa')),
            ],
        ),
        migrations.CreateModel(
            name='ConversaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.conversa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='conversa',
            name='usuario',
            field=models.ManyToManyField(related_name='conversas', through='forum.ConversaUsuario', to='usuario.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_comentario', models.TextField()),
                ('data_comentario', models.DateField(default=django.utils.timezone.now)),
                ('imagem_comentario', models.ImageField(blank=True, null=True, upload_to='blog/comentario/%Y/%m')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.postagem')),
            ],
        ),
    ]
