# Generated by Django 4.0.4 on 2022-06-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_conversausuario_ultimo_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversausuario',
            name='ultimo_acesso',
            field=models.DateField(default='2002-02-02'),
        ),
    ]
