# Generated by Django 4.0.4 on 2022-06-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_conversausuario_ultimo_acesso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversausuario',
            name='ultimo_acesso',
        ),
    ]
