# Generated by Django 4.0.4 on 2022-06-02 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_conversausuario_ultimo_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversausuario',
            name='ultimo_acesso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
