# Generated by Django 4.0.4 on 2022-04-29 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=250)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('sobrenome', models.CharField(max_length=250)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('celular', models.CharField(blank=True, max_length=15)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.endereco')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.estadocivil')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.genero')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_endereco', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('senha', models.CharField(max_length=250)),
                ('img_usuario', models.ImageField(blank=True, null=True, upload_to='img_perfis/%Y/%m')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='endereco',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.estado'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='tipo_endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.tipoendereco'),
        ),
    ]
