# Generated by Django 4.0.4 on 2022-04-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='img_usuario',
            field=models.ImageField(blank=True, default='img_perfis/comum.png', null=True, upload_to='img_perfis/%Y/%m'),
        ),
    ]
