# Generated by Django 4.0.4 on 2022-04-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_img_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_licenced',
            field=models.BooleanField(default=False),
        ),
    ]
