# Generated by Django 4.0.4 on 2022-05-31 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_is_licenced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='genero',
        ),
    ]
