# Generated by Django 4.0.4 on 2022-05-31 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_pessoa_celular_remove_pessoa_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='tipo_endereco',
        ),
        migrations.DeleteModel(
            name='EstadoCivil',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='TipoEndereco',
        ),
    ]
